blog/urls.py
from django.urls import path

from blog.views import (
    IndexView,
    BlogListView,
    SearchPostView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
    BlogDetailView,
    ContactView,
    CategoryListView,
    TagListView,
    CategoryPostView,
    TagPostView,
    CommentFormView,
#    comment_approve,
    comment_remove,
#    ReplyFormView,
#    reply_approve,
#    reply_remove,
)


app_name = 'blog'
urlpatterns = [
    path('', IndexView.as_view(),name="index"),
    path('blog/', BlogListView.as_view(),name="blog"),
    path('search/', SearchPostView.as_view(), name='search_post'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(),name="blog_detail"),
    path('blog_create/', BlogCreateView.as_view(),name="blog_create"),
    path('blog_update/<int:pk>/', BlogUpdateView.as_view(),name="blog_update"),
    path('blog_delete/<int:pk>/', BlogDeleteView.as_view(),name="blog_delete"),
    path('contact/', ContactView.as_view(),name="contact"),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('category/<str:category_slug>/',
         CategoryPostView.as_view(), name='category_post'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
    path('comment/<int:pk>/', CommentFormView.as_view(), name='comment_form'),
##    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
##    path('reply/<int:pk>/', ReplyFormView.as_view(), name='reply_form'),
##    path('reply/<int:pk>/approve/', reply_approve, name='reply_approve'),
##    path('reply/<int:pk>/remove/', reply_remove, name='reply_remove'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.sitemaps.views import sitemap
from .feeds import RssLatestPostsFeed, AtomLatestPostsFeed
from .sitemaps import (
    BlogPostSitemap,
    StaticViewSitemap,
)

from . import settings_common, settings_dev


sitemaps = {
    'blog': BlogPostSitemap,
    'static': StaticViewSitemap,
}


urlpatterns = [
#    path('admin/', admin.site.urls),
    path('control/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('feed/rss/', RssLatestPostsFeed()),
    path('feed/atom/', AtomLatestPostsFeed()),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('markdownx/', include('markdownx.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
from accounts.models import CustomUser
from django.utils import timezone

#from markdownx.models import MarkdownxField


#class ContentImage(models.Model):
#    post = models.ForeignKey(BlogPost, on_delete=models.PROTECT)
#    content_image = models.ImageField(upload_to='post_content_images/')


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class BlogPost(models.Model):
    """ブログ モデル"""
    user = models.ForeignKey(CustomUser, verbose_name='User', on_delete=models.PROTECT)
    category = models.CharField(Category, blaink=True)  # on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(verbose_name='Title', max_length=255)
##    content = MarkdownxField(verbose_name='Content', help_text='Markdown形式で記述してください。')
    content = models.TextField(verbose_name='Content', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='Created_at', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Updated_at', auto_now=True)
    published_at = models.DateTimeField(verbose_name='Published_at', blank=True, null=True)
    is_public = models.BooleanField(verbose_name='Is_public', default=False)
##    image = models.ImageField(upload_to='post_images/', null=True, blank=True)

    class Meta:
        verbose_name_plural = 'BlogPost'
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        BlogPost, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=50)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
#    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-timestamp']

#    def approve(self):
#        self.approved = True
#        self.save()

    def __str__(self):
        return self.text


#class Reply(models.Model):
#    comment = models.ForeignKey(
#        Comment, on_delete=models.CASCADE, related_name='replies')
#    author = models.CharField(max_length=50)
#    text = models.TextField()
#    timestamp = models.DateTimeField(auto_now_add=True)
#    approved = models.BooleanField(default=False)
#
#    def approve(self):
#        self.approved = True
#        self.save()
#
#    def __str__(self):
#        return self.text

blog/forms.py
from django import forms
from django.core.mail import EmailMessage
from django.forms import ModelForm, TextInput, Textarea
from blog.models import Comment, BlogPost     # Reply
#from markdownx.fields import MarkdownxFormField
from markdownx.widgets import MarkdownxWidget


class ContactForm(forms.Form):
    name = forms.CharField(label='Full Name', max_length=30)
    email = forms.EmailField(label='Email Address',)
    subject = forms.CharField(label='Subject', max_length=30)
    message = forms.CharField(label='Message', widget=forms.Textarea)

    def __init__(self, *args, **kwrgs):
        super().__init__(*args, **kwrgs)

        self.fields['name'].widget.attrs['class'] = 'form-control-9'
        self.fields['name'].widget.attrs['placeholder'] = 'Please enter your name.'

        self.fields['email'].widget.attrs['class'] = 'form-control-11'
        self.fields['email'].widget.attrs['placeholder'] = 'Please enter your email address.'

        self.fields['title'].widget.attrs['class'] = 'form-control-11'
        self.fields['title'].widget.attrs['placeholder'] = 'Please enter your title.'

        self.fields['message'].widget.attrs['class'] = 'form-control-9'
        self.fields['message'].widget.attrs['placeholder'] = 'Please enter your message.'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名： {0}\nメールアドレス： {1}\nメッセージ：　{2}'.format(name, email, message)
        from_email = 'gattionobianco22@gmail.com'
        to_list = [
            'gattinobianco22@gmail.com'
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(
            subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list
            )
        message.send()


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text')
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Please enter your name.',
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Please enter your comments.',
            }),
        }
        labels = {
            'author': '',
            'text': '',
        }


#class ReplyForm(ModelForm):
#    class Meta:
#        model = Reply
#        fields = ('author', 'text')
#        widgets = {
#            'author': TextInput(attrs={
#                'class': 'form-control',
#                'placeholder': 'Please enter your name.',
#            }),
#            'text': Textarea(attrs={
#                'class': 'form-control',
#                'placeholder': 'Please enter your comments.',
#            }),
#        }
#        labels = {
#            'author': '',
#            'text': '',
#        }


class BlogCreateForm(forms.ModelForm):
#    text = MarkdownxFormField()

    class Meta:
        model = BlogPost
        fields = ('title', 'category', 'tag', 'content', 'is_public')
#        fields = '__all__'
##        widgets = {
##            'content' : MarkdownxWidget(attrs={'class': 'textarea'})
##        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

blog/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from django.urls import reverse_lazy
from django.views import generic

from blog.forms import ContactForm , CommentForm, BlogCreateForm  # ReplyForm

from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin

from django.db.models import Count, Q
from django.http import Http404
#from django.views.generic.detail import DetailView
#from django.views.generic.list import ListView
#from django.views.generic.edit import CreateView

from blog.models import Category, Tag, BlogPost, Comment  # Reply


logger = logging.getLogger(__name__)


class IndexView(generic.TemplateView):
    template_name = 'index.html'


class BlogListView(generic.ListView):
    model = BlogPost
    template_name = 'blog.html'
    paginate_by = 3

    def get_queryset(self):
        blogs = BlogPost.objects.order_by('-created_at')
        return blogs


class SearchPostView(generic.ListView):
    model = BlogPost
    template_name = 'search_post.html'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        lookups = (
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(category__name__icontains=query) |
            Q(tags__name__icontains=query)
        )
        if query is not None:
            qs = super().get_queryset().filter(lookups).distinct()
            return qs
        qs = super().get_queryset()
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context


class BlogDetailView(generic.DetailView):
    model = BlogPost
    slug_field = 'title'
    slug_url_kwarg = 'title'
    template_name = 'blog_detail.html'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_public and not self.request.user.is_authenticated:
            raise Http404
        return obj


class CategoryListView(generic.ListView):
    queryset = Category.objects.annotate(
        num_posts=Count('blog_post', filter=Q(blog_post__is_public=True)))


class TagListView(generic.ListView):
    queryset = Tag.objects.annotate(num_posts=Count(
        'blog_post', filter=Q(blog_post__is_public=True)))


class CategoryPostView(generic.ListView):
    model = BlogPost
    template_name = 'category_post.html'

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


class TagPostView(generic.ListView):
    model = BlogPost
    template_name = 'tag_post.html'

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = super().get_queryset().filter(tags=self.tag)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context



class CommentFormView(generic.CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment.post = get_object_or_404(BlogPost, pk=post_pk)
        comment.save()
        return redirect('blog:blog_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_pk = self.kwargs['pk']
        context['blog_post'] = get_object_or_404(BlogPost, pk=post_pk)
        return context


#@login_required
#def comment_approve(request, pk):
#    comment = get_object_or_404(Comment, pk=pk)
#    comment.approve()
#    return redirect('blog:blog_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:blog_detail', pk=comment.post.pk)


#class ReplyFormView(CreateView):
#    model = Reply
#    form_class = ReplyForm
#
#    def form_valid(self, form):
#        reply = form.save(commit=False)
#        comment_pk = self.kwargs['pk']
#        reply.comment = get_object_or_404(Comment, pk=comment_pk)
#        reply.save()
#        return redirect('blog:blog_detail', pk=reply.comment.post.pk)
#
#    def get_context_data(self, **kwargs):
#        context = super().get_context_data(**kwargs)
#        comment_pk = self.kwargs['pk']
#        context['comment'] = get_object_or_404(Comment, pk=comment_pk)
#        return context
#
#
#@login_required
#def reply_approve(request, pk):
#    reply = get_object_or_404(Reply, pk=pk)
#    reply.approve()
#    return redirect('blog:blog_detail', pk=reply.comment.post.pk)
#
#
#@login_required
#def reply_remove(request, pk):
#    reply = get_object_or_404(Reply, pk=pk)
#    reply.delete()
#    return redirect('blog:blog_detail', pk=reply.comment.post.pk)


class ContactView(generic.FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('blog:contact')

    def form_valid(self, form):
        form.send_mail()
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)


class BlogCreateView(LoginRequiredMixin, generic.CreateView):
    model = BlogPost
    template_name = 'blog_create.html'
    form_class = BlogCreateForm
    success_url = reverse_lazy('blog:blog')

    def form_valid(self, form):
        blog = form.save(commit=False)
        blog.user = self.request.user
        blog.save()
        messages.success(self.request, 'ブログを投稿しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'ブログの投稿に失敗しました。')
        return super().form_invalid(form)


class BlogUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = BlogPost
    template_name = 'blog_update.html'
    form_class = BlogCreateForm

    def get_success_url(self):
        return reverse_lazy('blog:blog_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, 'ブログを更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'ブログの更新に失敗しました。')
        return super().form_invalid(form)


class BlogDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = BlogPost
    template_name = 'blog_delete.html'
    success_url = reverse_lazy('blog:blog')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'ブログを削除しました。')
        return super().delete(request, *args, **kwargs)

blog/templates/snippets/blog_list.html
{% load markdown_html %}
    <!-- highlight.js関連の読み込み -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/dracula.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

    {% for post in object_list %}

    <style type="text/css">
    .textOverflow {
        overflow: hidden;
        white-space: nowrap;
        text-overflow:ellipsis;
        }
    </style>

    {% if user.is_authenticated or post.is_public %}
        <!-- Blog Entries Column -->
        <div class="col-md-8">
            <!-- Blog Post -->
            <div class="card mb-4">
                {% if post.image %}
                    <img class="card-img-top" src="{{ post.image.url }}" alt="{{ post.title }}" width="750" height="300">
                {% else% }
                    <img class="card-img-top" src="{% static '/img/default_750_300.jpg' %}" alt>
                {% endif %}
                <div class="card-body">
                    {% if not post.is_public %}
                        <h5><span class="badge badge-secondary">Draft</span></h5>
                    {% endif %}
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text">
                        {{ post.content | markdown_to_html }}
                    </p>
                </div>
                <a href="{% url 'web:blog_detail' post.id %}" class="btn btn-primary">Read More →
                </a>
            </div>
            <div class="card-footer text-muted">
                "Posted on "
                {{ post.created_at }}
                "by "
                {{ post.user }}
            </div>
        </div>
    {% endif %}

{% empty %}
        <div class="col-md-8">
            <!-- Blog Post -->
            <div class="card mb-4">
                <img class="card-img-top" src="{% static '/img/default_750_300.jpg' %}" alt="Commin Soon">
                <div class="card-body">
                    <h2 class="card-title">Comming Soon</h2>
                    <p class="card-text">
                    </p>
                    <a href="{% url 'web:blog_detail' post.id %}" class="btn btn-primary disabled">Read More →</a>
                </div>
                <div class="card-footer text-muted">
                </div>
            </div>
        </div>

{% endfor %}

blog/templates/snippets/comment_form.html
<!-- Comments Form -->
<div class="card my-4">
    <h5 class="card-header">Leave a Comment:</h5>
    <div class="card-body">
        <form method="POST">{% csrf_token %}{{ form.as_p }}

            <div class="control-group form-group">
                <div class="controls">
                    <label>Full Name * :</label>
                    <input type="text" class="form-control" id="name" required="" data-validation-required-message="Please enter your name." aria-invalid="false">
                    <p class="help-block"></p>
                </div>
            </div>

            <div class="control-group form-group">
                <div class="controls">
                <label>Email Address :</label>
                <input type="email" class="form-control" id="email" required="">
                <div class="help-block">
                </div>
            </div>

            <div class="control-group form-group">
                <div class="controls">
                    <label>Message * :</label>
                    <textarea rows="3" class="form-control" id="message" required="" data-validation-required-message="Please enter your comment" maxlength="999" style="resize:none"></textarea>
                    <div class="help-block">
                    </div>
                </div>
            </div>
            <div id="success">
            </div>

            <!-- For success/fail messages -->
            <button type="submit" class="btn btn-primary" id="submit">Submit</button>
            <button type="reset" class="btn btn-light" id="cancel">Cancel</button>
        </form>
    </div>
</div>

blog/templates/snippets/comment_view.html
{% load markdown_html %}

<!-- {% for post in object_list %} -->
{% for comment in post.comments.all %}
<!-- {% if user.is.authenticated or comment.approved %} -->

<!-- Single Comment -->
    <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="{% static 'img/default_50_50.jpg' %}" alt="">
        <div class="media-body">
            <h5 class="mt-0">{{ comment.author }}</h5> -
            {{ comment.timestamp }}
<!--            <p>{{ comment.text|linebreaksbr }}</p> -->
            {{ comment.text | markdown_to_html_with_escape }}
            {% if user.is.authenticated %}
                <a href="{% url 'blog_comment_remove' %}" type="button" class="btn btn-danger" id="comment_remove" >Delete</a>
            {% endif %}
        </div>
    </div>
{% empty %}
    <div class="media mb-4">
        <div class="media-body">
            "コメントはまだありません。"
        </div>
    </div>
{% endfor %}

blog/templates/snippets/contact_form.html
<div class="col-lg-8 mb-4">
    <h3>Send us a Message</h3>

    <form name="sentMessage" id="contactForm" novalidate="">
        <div class="control-group form-group">
            <div class="controls">
                <label>Full Name:</label>
                <input type="text" class="form-control" id="name" required="" data-validation-required-message="Please enter your name." aria-invalid="false">
                <p class="help-block"></p>
            </div>
        </div>

        <div class="control-group form-group">
            <div class="controls">
                <label>Email Address:</label>
                <input type="email" class="form-control" id="email" required="" data-validation-required-message="Please enter your email address.">
                <div class="help-block">
                </div>
            </div>
        </div>

        <div class="control-group form-group">
            <div class="controls">
                <label>Title:</label>
                <input type="title" class="form-control" id="title" required="" data-validation-required-message="Please enter your title.">
                <div class="help-block">
                </div>
            </div>
        </div>

        <div class="control-group form-group">
            <div class="controls">
                <label>Message:</label>
                <textarea rows="10" cols="100" class="form-control" id="message" required="" data-validation-required-message="Please enter your message" maxlength="999" style="resize:none"></textarea>
                <div class="help-block">
                </div>
            </div>
        </div>
        <div id="success">
        </div>
        <!-- For success/fail messages -->
        <button type="submit" class="btn btn-primary" id="sendMessageButton">Send Message</button>
        <button type="reset" class="btn btn-light" id="CancelButton">Cancel</button>
    </form>
</div>

blog/templates/snippets/features_section.html
<div call="col-lg=6">
    <h2>しろねこプロダクトの開発環境</h2>
    <p>WEBサイト／サービス等を制作するにあたり、下記の環境を利用しています。</p>
    <ul>
        <li>
            ::marker
            <a href ="https://www.python.org/"><strong>python</strong></a>
            <i class="fab fa-python"></i></a>
        </li>
        <li>
            ::marker
            <a href="https://www.djangoproject.com/">django</a>
        </li>
        <li>
            ::marker
            <a href="https://www.postgresql.org/">PostgreSQL</a>
        </li>
        <li>
            ::marker
            <a href="https://nginx.org/en/">Nginx</a>
        </li>
        <li>
            ::marker
            <a href="https://gunicorn.org/">Gunicorn</a>
        </li>
        <li>
            ::marker
            <a href="https://aws.amazon.com/jp/">AWS</a>
            <i class="fab fa-aws"></i>
        </li>
        <li>
            ::marker
            Docker
            <a href="https://www.docker.com/">Docker</a>
            <i class="fab fa-docker"></i>
        </li>
        <li>
            ::marker
            <a href="https://github.co.jp/">GitHub</a>
            <i class="fab fa-github"></i>
        </li>
        <li>
            ::marker
            <a href="https://www.sourcetreeapp.com/">Sourcetree</a>
            <i class="fab fa-sourcetree"></i>
        </li>
    </ul>
    <p>
    </p>
</div>

<div class="col-lg-6">
    <img class="ims-fuid rounded" src="{% static 'img/default_700_450.jpg' %}" alt>
</div>

blog/templates/snippets/nav_bar.html
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'web:index' %}">しろねこプロダクト</a>
        <button class="navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navibarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link disabled" href="{% url 'web:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="{% url 'web:service' %}">Service</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="{% url 'web:portfolio_list' %}">Portfolio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'web:contact' %}">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'web:blog' %}">Blog</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"  href="#" if="navbarDropdownPages" data-toggle="dropdown" aria-hasopup="true" aria=expanded="false">Other Pages</a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPages">
                        <a class="dropdown-item disabled" href="{% url 'web:FAQ' %}">FAQ</a>
                        <a class="dropdown-item disabled" href="{% url 'web:disclaimer' %}">Disclaimer</a> <!-- 免責事項 -->
                        <a class="dropdown-item disabled" href="{% url 'web:privacy_policy' %}">Privacy Policy</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"  href="#" if="navbarDropdownPages" data-toggle="dropdown" aria-hasopup="true" aria=expanded="false">Administration</a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPages">
                        {% if user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'account_logout' %}">Log Out</a>
                            <a class="dropdown-item" href="{% url 'blog:blog_create' %}">Write Brogs</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'account_signup' %}">Sign Up</a>
                            <a class="dropdown-item" href="{% url 'account_login' %}">Log In</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

blog/templates/snippets/side_widget.html
<!-- Sideber widget Column -->
<!-- Search widget -->
<div class="card-mb-4">
    <h5 class="card-header">Search</h5>
        <div class="card-body">
            <div class="input-group">
                <form class="form-inline" action="{% url 'blog:search_post' %} method="GET">
                    <input type="text" class="form-control" type="serch" name="q" value="{{ request.GET.q }}" placeholder="Search for..." aria-label="Search">
                    <span class="input-group-append">
                        <button class="btn btn-primary" type="submit">Go!</button>
                    </span>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Categories Widget-->
<div class="card my-4">
    <h5 class="card-header">Categories</h5>
    <div class="card-body">
        <div class="row">
            <!-- 登録されたカテゴリが複数表示される -->
            <div class="col-lg-6">
                <ul class="list-group list-group-flush">
                    <!-- {% for category in categories|discsort:"id" %} --> <!-- id順でならべる場合 -->
                    {% for tag in tags|discsortreversed:"num_posts|slice:":1" %} <!-- 数の多い順（降順）で並べる -->
                    <li class="list-group-item d-frex justify-content-between align-items-center">
                        <a href="{% url 'blog:category_post' category.slug %}" class="card-link">{{ category.name }}</a>
                        <span class="badge badge-primary badge-pill">{{ category.num_posts }}</span>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Tags Widget-->
<div class="card my-4">
    <h5 class="card-header">Tags</h5>
    <div class="card-body">
        <div class="row">
            <!-- 登録されたタグが複数表示される -->
            <div class="col-lg-6">
                <ul class="list-group list-group-flush">
                    {% for tag in tags|discsortreversed:"num_posts|slice:":1" %}
                    <li class="list-group-item d-frex justify-content-between align-items-center">
                        <a href="{% url 'blog:tag_post' tag.slug %}" class="card-link">{{ tag.name }}</a>
                        <span class="badge badge-primary badge-pill">{{ tag.num_posts }}</span>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>